-- نظام التعليقات العامة وملاحظات الكتب لموقع GitHub Pages.
-- نفّذ هذا الملف من SQL Editor داخل مشروع Supabase.

create table if not exists public.general_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 60),
  comment text not null check (char_length(btrim(comment)) between 3 and 1000),
  created_at timestamptz not null default now(),
  approved boolean not null default false
);

create table if not exists public.book_feedback (
  id bigint generated by default as identity primary key,
  book_id text not null check (char_length(btrim(book_id)) between 1 and 160),
  book_title text not null check (char_length(btrim(book_title)) between 1 and 500),
  reviewer_name text not null check (char_length(btrim(reviewer_name)) between 2 and 60),
  reviewer_email text check (
    reviewer_email is null
    or (
      char_length(btrim(reviewer_email)) between 3 and 254
      and btrim(reviewer_email) ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    )
  ),
  page_number text not null check (char_length(btrim(page_number)) between 1 and 20),
  issue_type text not null check (issue_type in (
    'خطأ في الترجمة',
    'مصطلح علمي',
    'خطأ علمي',
    'معادلة أو رمز',
    'شكل أو صورة',
    'تعليق على الشكل',
    'خطأ إملائي',
    'خطأ نحوي أو لغوي',
    'تنسيق الصفحة',
    'نص غير واضح',
    'جزء مفقود',
    'مرجع أو اقتباس',
    'اقتراح لتحسين الأسلوب',
    'ملاحظة عامة',
    'أخرى'
  )),
  comment text not null check (char_length(btrim(comment)) between 5 and 3000),
  suggested_correction text check (
    suggested_correction is null
    or char_length(suggested_correction) <= 3000
  ),
  wants_contact boolean not null default false,
  created_at timestamptz not null default now(),
  approved boolean not null default false,
  status text not null default 'new' check (
    status in ('new', 'reviewing', 'accepted', 'applied', 'rejected')
  ),
  constraint contact_requires_email check (
    not wants_contact or reviewer_email is not null
  )
);

create index if not exists general_comments_public_order_idx
  on public.general_comments (approved, created_at desc);

create index if not exists book_feedback_work_queue_idx
  on public.book_feedback (status, created_at desc);

alter table public.general_comments enable row level security;
alter table public.book_feedback enable row level security;

-- أزل الصلاحيات الافتراضية الواسعة ثم أعد أقل قدر مطلوب.
revoke all on table public.general_comments from anon, authenticated;
revoke all on table public.book_feedback from anon, authenticated;

grant select (id, name, comment, created_at, approved)
  on table public.general_comments to anon, authenticated;
grant insert (name, comment)
  on table public.general_comments to anon, authenticated;

grant insert (
  book_id,
  book_title,
  reviewer_name,
  reviewer_email,
  page_number,
  issue_type,
  comment,
  suggested_correction,
  wants_contact
) on table public.book_feedback to anon, authenticated;

revoke all on sequence public.general_comments_id_seq from anon, authenticated;
revoke all on sequence public.book_feedback_id_seq from anon, authenticated;
grant usage on sequence public.general_comments_id_seq to anon, authenticated;
grant usage on sequence public.book_feedback_id_seq to anon, authenticated;

drop policy if exists public_read_approved_general_comments
  on public.general_comments;
create policy public_read_approved_general_comments
  on public.general_comments
  for select
  to anon, authenticated
  using (approved = true);

drop policy if exists public_submit_general_comment
  on public.general_comments;
create policy public_submit_general_comment
  on public.general_comments
  for insert
  to anon, authenticated
  with check (approved = false);

drop policy if exists public_submit_book_feedback
  on public.book_feedback;
create policy public_submit_book_feedback
  on public.book_feedback
  for insert
  to anon, authenticated
  with check (approved = false and status = 'new');

-- لا توجد سياسة SELECT لملاحظات الكتب؛ لذلك لا يستطيع الزوار قراءتها.
-- لا توجد سياسات UPDATE أو DELETE للزوار في أي من الجدولين.
