-- إضافة مستقلة: لا تغيّر جدولي التعليقات والمراجعات أو سجلاتهما.
create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  request_type text not null check (request_type in ('translation', 'download', 'source', 'general')),
  book_id text check (book_id is null or char_length(btrim(book_id)) between 1 and 160),
  book_title text check (book_title is null or char_length(btrim(book_title)) between 1 and 500),
  name text check (name is null or char_length(btrim(name)) between 2 and 60),
  email text not null check (
    char_length(btrim(email)) between 3 and 254
    and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  material_title text check (material_title is null or char_length(btrim(material_title)) between 1 and 500),
  author text check (author is null or char_length(btrim(author)) between 1 and 200),
  original_language text check (original_language is null or char_length(btrim(original_language)) between 1 and 80),
  subject_area text check (subject_area is null or char_length(btrim(subject_area)) between 1 and 160),
  source_url text check (source_url is null or (char_length(source_url) <= 2000 and source_url ~* '^https?://[^[:space:]/@?#]+([/?#][^[:space:]]*)?$')),
  message text not null check (char_length(btrim(message)) between 5 and 3000),
  notes text check (notes is null or char_length(notes) <= 1000),
  created_at timestamptz not null default now(),
  status text not null default 'new' check (status in ('new', 'reviewing', 'answered', 'closed')),
  constraint request_book_required check (request_type not in ('download', 'source') or (book_id is not null and book_title is not null)),
  constraint translation_details_required check (
    request_type <> 'translation' or (material_title is not null and original_language is not null and subject_area is not null)
  )
);

create index if not exists contact_requests_queue_idx on public.contact_requests (status, created_at desc);
alter table public.contact_requests enable row level security;
revoke all on table public.contact_requests from anon, authenticated;
grant insert (request_type, book_id, book_title, name, email, material_title, author, original_language, subject_area, source_url, message, notes)
  on public.contact_requests to anon, authenticated;
revoke all on sequence public.contact_requests_id_seq from anon, authenticated;
grant usage on sequence public.contact_requests_id_seq to anon, authenticated;

drop policy if exists public_submit_contact_request on public.contact_requests;
create policy public_submit_contact_request on public.contact_requests
  for insert to anon, authenticated with check (status = 'new');

-- لا توجد صلاحيات أو سياسات SELECT/UPDATE/DELETE للزوار: الطلبات والبريد خاصة بالإدارة.
